-- 코드를 입력하세요
SELECT car.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR car, CAR_RENTAL_COMPANY_RENTAL_HISTORY history
WHERE car.CAR_ID = history.CAR_ID 
    AND CAR_TYPE = '세단' 
    AND history.START_DATE BETWEEN '2022-10-01' and '2022-10-31'
GROUP BY car.CAR_ID
ORDER BY car.CAR_ID DESC;